fix

diff --git a/.github/workflows/build-deploy-java-app.yaml b/.github/workflows/build-deploy-java-app.yaml
--- a/.github/workflows/build-deploy-java-app.yaml
+++ b/.github/workflows/build-deploy-java-app.yaml
@@ -1,16 +1,21 @@
 name: Build and Deploy Java app
+
 on:
   push:
     branches:
       - work-flow-update
+
 permissions:
   contents: write
+
 jobs:
   build:
     runs-on: ubuntu-latest
+    
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
+
       - name: Set up Java
         uses: actions/setup-java@v3
         with:
@@ -40,7 +45,7 @@ jobs:
           context: ./myapp
           file: ./myapp/Dockerfile
           push: false
-          tags: justme2024/hello-world:${{ env.NEW_VERSION }}
+          tags: ${DOCKER_HUB_USERNAME}/hello-world:${{ env.NEW_VERSION }}
           build-args: VER=${{ env.NEW_VERSION }}
           
       - name: Login to Docker Hub
@@ -51,12 +56,12 @@ jobs:
           
       - name: Push Docker Image to Docker Hub
         run: |
-          docker push justme2024/hello-world:${{ env.NEW_VERSION }}
+          docker push ${DOCKER_HUB_USERNAME}/hello-world:${{ env.NEW_VERSION }}
           
       - name: Remove local Docker image (to force pull)
         run: |
-	  docker rmi ${DOCKER_HUB_USERNAME}/hello-world:${{ env.NEW_VERSION }} || echo "Image not found locally"
+          docker rmi ${DOCKER_HUB_USERNAME}/hello-world:${{ env.NEW_VERSION }} || echo "Image not found locally"
           
       - name: Run Docker Image (non-root)
         run: |
-          docker run --rm --user 1000:1000 justme2024/hello-world:${{ env.NEW_VERSION }}
+          docker run --rm --user 1000:1000 ${DOCKER_HUB_USERNAME}/hello-world:${{ env.NEW_VERSION }}
